service: api-service-blockconvey-iso

runtime: nodejs20

instance_class: F4_1G

automatic_scaling:
  target_cpu_utilization: 0.85
  min_instances: 1
  max_instances: 10

handlers:

  - url: /static
    static_dir: dist/static
    http_headers:
      Cache-Control: "public, max-age=31536000"


  - url: /(.*\.(js|css|png|jpg|svg|ico|json))
    static_files: dist/\1
    upload: dist/.*\.(js|css|png|jpg|svg|ico|json)
    http_headers:
      Cache-Control: "public, max-age=31536000"


  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always


env_variables:
  NODE_ENV: production